[package]
version = "1.0.1" # Semantic Versioning is used: https://semver.org/

# These fields are used primarily for display in the extension browser UI.
title = "Example C++ Extension: USD"
description = "Demonstrates how to create a C++ plugin that can interact with the current USD stage."
category = "Example"
keywords = ["example", "C++", "cpp", "USD"]
icon = "data/icon.png"
preview_image = "data/preview.png"
changelog = "docs/CHANGELOG.md"
readme  = "docs/README.md"
authors = ["David Bosnich <dbosnich@nvidia.com>"]
repository = "https://github.com/NVIDIA-Omniverse/kit-extension-template-cpp"

[dependencies]
"omni.usd" = {}

# Define the Python modules that this extension provides.
# C++ only extensions need this just so tests don't fail.
[[python.module]]
name = "omni.example.deps"

# Define the C++ plugins that this extension provides.
[[native.plugin]]
path = "bin/*.plugin"